backend:
  name: github
  repo: codeforharima/codeforharima.github.io # ← リポジトリ名
  branch: main # ← 公開用ブランチ

media_folder: "content/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "ブログ"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "日付", name: "date", widget: "datetime" }
      - { label: "本文", name: "body", widget: "markdown" }
